name: reverse
on: push
jobs:
  test_revese:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: make install
      - name: Run Lint
        run: make lint
