name: reverse
on: push
jobs:
  test_revese:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install
        run: make install
      - name: Run Lint
        run: make lint
